### ISSUE TITLE
Not able to see entries collection

### ISSUE THREAD

**Issue by FJLopezGarcia** [ebenezerdon/journal-rest-api#1]
HI @ebenezerdon  hope you are doing well!! 

I am following your blog https://blog.logrocket.com/rest-api-firebase-cloud-functions-typescript-firestore/ to create a cloud function storing the data in firebase but when I request the https://us-central1-e-commerce-b8a93.cloudfunctions.net/app/entries (POST) from postman, I received a 200 OK but the collection doesn't appear in my Cloud Firestore. Do you know what could be the reason?

![image](https://user-images.githubusercontent.com/6631983/118682953-38104300-b801-11eb-8991-cb30eb754b09.png)
![image](https://user-images.githubusercontent.com/6631983/118683240-81609280-b801-11eb-88d5-68e3c5d3cc49.png)

Also, when I run the https://us-central1-e-commerce-b8a93.cloudfunctions.net/app/entries to GET the collection values... i receive an unauthorised error

![image](https://user-images.githubusercontent.com/6631983/118683677-def4df00-b801-11eb-9152-b9815f9c6d06.png)
 
Thanks a lo for your help!!
Javi

**Comment by ebenezerdon** [comment]
Hi @FJLopezGarcia, can you send me a screenshot of your controller?

Also, I have a video version of the tutorial. Maybe that could help explain things more clearly: https://youtu.be/T8SZv6h2WbY

**Comment by FJLopezGarcia** [comment]
Hi @ebenezerdon  here you have the entryController.ts: 
![image](https://user-images.githubusercontent.com/6631983/118718285-5ab55280-b827-11eb-8399-665d947bfbcb.png)
![image](https://user-images.githubusercontent.com/6631983/118718336-6739ab00-b827-11eb-93fa-30de49c08b45.png)
I will take a look at your video tomorrow my morning!! thanks a lot for your support!

**Comment by FJLopezGarcia** [comment]
Hi @ebenezerdon thanks for the video. I was calling wrong the cloud function from postman. 
Also I noticed an error in your code:
![image](https://user-images.githubusercontent.com/6631983/118889878-134dc580-b8fe-11eb-9184-1dc50c6a5d41.png)

I am now subscribed to your channel.

Thanks a lot!!

**Comment by ebenezerdon** [comment]
> Hi @ebenezerdon thanks for the video. I was calling wrong the cloud function from postman.
> Also I noticed an error in your code:
> ![image](https://user-images.githubusercontent.com/6631983/118889878-134dc580-b8fe-11eb-9184-1dc50c6a5d41.png)
> 
> I am now subscribed to your channel.
> 
> Thanks a lot!!

Thanks, @FJLopezGarcia! I'm glad I was able to help.
And thanks for pointing out the typo. I've fixed it.
