### ISSUE TITLE
Entrytype defined as number is stored in firebase as string

### ISSUE THREAD

**Issue by FJLopezGarcia** [ebenezerdon/journal-rest-api#2]
HI @ebenezerdon do you know the reason why having and EntryType defined as number in firebase is stored as string?
![image](https://user-images.githubusercontent.com/6631983/119140980-0a1b4080-ba45-11eb-9dbd-6fbdc21d489a.png)

![image](https://user-images.githubusercontent.com/6631983/119141077-23bc8800-ba45-11eb-8f6e-6d0c4ad5f1de.png)

![image](https://user-images.githubusercontent.com/6631983/119141032-17d0c600-ba45-11eb-8f00-91d3bca58b32.png)

Thanks a lot

**Comment by ebenezerdon** [comment]
Hi @FJLopezGarcia, the `type` in your codebase is for TypeScript, not Firestore. Firestore's only job, in this case, is to receive whatever data you send to it. You'll have to add type validation as middleware or do the type-check in your controller.

I'm guessing Postman's x-www-form-field is sending your data as `string`. Have you tried using raw JSON for your request?
